import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {terrain} from './physics.mjs';
export function createRenderer(canvas:HTMLCanvasElement,objects:any[]){
 const gl=new T.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});gl.setPixelRatio(Math.min(devicePixelRatio,1.5));gl.setClearColor(0x87b9d0);const scene=new T.Scene();scene.fog=new T.FogExp2(0xb6d2df,.0019);const camera=new T.PerspectiveCamera(72,1,.1,2400);const light=new T.DirectionalLight(0xffefd9,2.4);light.position.set(-90,180,100);scene.add(light,new T.HemisphereLight(0xc7eaff,0x7296aa,2));const snow=new T.MeshStandardMaterial({color:0xe8f3f6,roughness:1});const ice=new T.MeshStandardMaterial({color:0xb8d6e3,roughness:.8});const dark=new T.MeshStandardMaterial({color:0x174449,roughness:1});const rock=new T.MeshStandardMaterial({color:0x647580,roughness:1});const orange=new T.MeshStandardMaterial({color:0xff632e,roughness:.8});
 const ground=new T.Mesh(new T.PlaneGeometry(5000,5000),snow);ground.rotation.x=-Math.PI/2;ground.position.y=-.25;scene.add(ground);
 const trackGeom=new T.PlaneGeometry(29,1800,1,160);trackGeom.rotateX(-Math.PI/2);const track=new T.Mesh(trackGeom,ice);track.position.y=-.13;scene.add(track);
 const leaves:T.BufferGeometry[]=[],caps:T.BufferGeometry[]=[];for(let j=0;j<3;j++){let g=new T.ConeGeometry(3-j*.6,5,5);g.translate(0,3+j*2,0);leaves.push(g);let c=new T.ConeGeometry(2.55-j*.5,3.5,5);c.translate(0,4+j*2,0);caps.push(c)}const leafGeometry=mergeGeometries(leaves)!,capGeometry=mergeGeometries(caps)!;leaves.concat(caps).forEach(g=>g.dispose());
 function tree(scale=1){const g=new T.Group();g.add(new T.Mesh(leafGeometry,dark),new T.Mesh(capGeometry,snow));g.scale.setScalar(scale);return g}
 const forest=new T.InstancedMesh(leafGeometry,dark,130),forestSnow=new T.InstancedMesh(capGeometry,snow,130);forest.frustumCulled=false;forestSnow.frustumCulled=false;scene.add(forest,forestSnow);const dummy=new T.Object3D();
 const obstacleMeshes=objects.map(o=>{let m:T.Object3D;if(o.type==='tree')m=tree(.9);else if(o.type==='rock'){m=new T.Mesh(new T.DodecahedronGeometry(1.65,0),rock);m.scale.set(1.4,.9,1);m.position.y=1}else{let g=new T.Group();let ramp=new T.Mesh(new T.BoxGeometry(7, .35,9),orange);ramp.rotation.x=.19;ramp.position.y=.9;g.add(ramp);for(let k=-1;k<=1;k++){let strip=new T.Mesh(new T.BoxGeometry(.22,.05,7),snow);strip.position.set(k*1.15,1.13,0);strip.rotation.x=.19;g.add(strip)}m=g}m.position.x=terrain(o.s)+o.x;m.position.z=-o.s;scene.add(m);return m});
 const mountains:T.Object3D[]=[];for(let i=0;i<15;i++){let m=new T.Mesh(new T.ConeGeometry(190+(i%3)*90,200+(i%5)*75,5),i%3===0?ice:snow);m.rotation.y=i*1.7;scene.add(m);mountains.push(m)}
 const finish=new T.Group();for(const x of [-14,14]){let m=new T.Mesh(new T.CylinderGeometry(.25,.25,10,6),orange);m.position.set(x,5,0);finish.add(m)}let bar=new T.Mesh(new T.BoxGeometry(28,1.5,.4),orange);bar.position.y=9;finish.add(bar);finish.position.set(terrain(7200),0,-7200);scene.add(finish);
 const skis=new T.Group();for(let x of [-.28,.28]){let ski=new T.Mesh(new T.BoxGeometry(.13,.045,1.8),orange);ski.position.set(x,-.84,-1.05);skis.add(ski)}camera.add(skis);scene.add(camera);
 const peers=new Map<string,T.Group>();const sparksGeom=new T.BufferGeometry();const sparkData=new Float32Array(60*3);sparksGeom.setAttribute('position',new T.BufferAttribute(sparkData,3));const sparks=new T.Points(sparksGeom,new T.PointsMaterial({color:0xffffff,size:.13,transparent:true}));camera.add(sparks);
 let lastW=0,lastH=0,frames=0,perfStart=performance.now();let reduced=false;
 function draw(p:any,others:any[],time:number,menu=false){let w=canvas.clientWidth,h=canvas.clientHeight;if(w!==lastW||h!==lastH){lastW=w;lastH=h;gl.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}const s=p.s;ground.position.z=-s;let arr=trackGeom.attributes.position;for(let i=0;i<arr.count;i++){let z=(i>>1)*1800/160-150;arr.setXYZ(i,(i%2?14.5:-14.5)+terrain(s+z),0,-s-z)}arr.needsUpdate=true;trackGeom.computeBoundingSphere();for(let i=0;i<130;i++){let z=Math.floor((s-70)/38)*38+(i>>1)*38;dummy.position.set(terrain(z)+(i%2?1:-1)*(22+(i*17%65)),0,-z);dummy.scale.setScalar(.7+(i%7)*.16);dummy.updateMatrix();forest.setMatrixAt(i,dummy.matrix);forestSnow.setMatrixAt(i,dummy.matrix)}forest.instanceMatrix.needsUpdate=true;forestSnow.instanceMatrix.needsUpdate=true;obstacleMeshes.forEach((m,i)=>{m.visible=objects[i].s>s-30&&objects[i].s<s+1300});mountains.forEach((m,i)=>m.position.set((i-7)*220,-70,-s-1450-Math.abs(i-7)*30));let air=p.air>0?Math.sin((1-p.air/1.55)*Math.PI)*6:0;camera.position.set(terrain(s)+p.x,2.2+air,-s+1);camera.rotation.set(0,0,0);camera.rotation.x=-.035;camera.rotation.z=-p.steer*.07;const elapsed=time-p.flipAt;if(p.flipped&&elapsed>=0&&elapsed<.7&&p.air>0)camera.rotation.x+=Math.PI*2*(elapsed/.7);camera.fov=72+(p.tier-1)*1.6;camera.updateProjectionMatrix();skis.rotation.z=Math.sin(time*4)*.025;skis.visible=!menu;
 let ids=new Set(others.map(q=>q.id));for(let [id,m]of peers)if(!ids.has(id)){scene.remove(m);peers.delete(id)}for(let q of others){let m=peers.get(q.id);if(!m){m=new T.Group();let mat=new T.MeshStandardMaterial({color:new T.Color().setHSL((peers.size*.23+.08)%1,.85,.56)});let body=new T.Mesh(new T.CapsuleGeometry(.45,.8,2,5),mat);body.position.y=1.2;m.add(body);let head=new T.Mesh(new T.SphereGeometry(.32,6,5),dark);head.position.y=2.12;m.add(head);for(let x of [-.4,.4]){let sk=new T.Mesh(new T.BoxGeometry(.18,.08,2.4),orange);sk.position.x=x;m.add(sk)}scene.add(m);peers.set(q.id,m)}m.position.set(terrain(q.s)+q.x,q.air>0?Math.sin((1-q.air/1.55)*Math.PI)*6:0,-q.s);m.rotation.z=-q.steer*.14;m.visible=Math.abs(q.s-s)<1200}
 const contact=others.some(q=>Math.abs(q.s-s)<2.5&&Math.abs(q.x-p.x)<1.2);sparks.visible=p.hit>0||p.boost>0||contact;if(sparks.visible){for(let i=0;i<60;i++){sparkData[i*3]=Math.sin(i*41+time*12)*1.8;sparkData[i*3+1]=Math.cos(i*27+time*8);sparkData[i*3+2]=-1-(i%12)/4}sparksGeom.attributes.position.needsUpdate=true}gl.render(scene,camera);frames++;if(time>0&&performance.now()-perfStart>4000){if(frames/(performance.now()-perfStart)*1000<38&&!reduced){gl.setPixelRatio(1);gl.setSize(w,h,false);reduced=true}frames=0;perfStart=performance.now()}}
 return {draw,destroy(){scene.traverse(o=>{const m=o as T.Mesh;if(m.geometry)m.geometry.dispose();if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>x.dispose())});gl.dispose()}};
}
