import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {QUALITY} from './quality.mjs';
import {introCamera} from './opponent-view.mjs';
import {createOpponents} from './opponents';
import {terrain} from './physics.mjs';
export function createRenderer(canvas:HTMLCanvasElement,objects:any[],quality:string="low"){
 const settings=QUALITY[quality]||QUALITY.low;
 const gl=new T.WebGLRenderer({canvas,antialias:quality!=="low",powerPreference:'high-performance'});gl.setPixelRatio(Math.min(devicePixelRatio,settings.pixelRatio));gl.setClearColor(0x87b9d0);const scene=new T.Scene();scene.fog=new T.FogExp2(0xb6d2df,.0019);const camera=new T.PerspectiveCamera(72,1,.1,2400);const light=new T.DirectionalLight(0xffefd9,2.4);light.position.set(-90,180,100);scene.add(light,new T.HemisphereLight(0xc7eaff,0x7296aa,2));gl.shadowMap.enabled=settings.shadows;gl.shadowMap.type=T.PCFSoftShadowMap;light.castShadow=settings.shadows;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-60,right:60,top:70,bottom:-70,near:1,far:400});light.shadow.bias=-.001;scene.add(light.target);gl.toneMapping=quality==='low'?T.NoToneMapping:T.ACESFilmicToneMapping;gl.toneMappingExposure=quality==='low'?1:1.05;
 const snow=new T.MeshStandardMaterial({color:0xe8f3f6,roughness:1});const ice=new T.MeshStandardMaterial({color:0xb8d6e3,roughness:.8});const dark=new T.MeshStandardMaterial({color:0x174449,roughness:1});const rock=new T.MeshStandardMaterial({color:0x647580,roughness:1});const orange=new T.MeshStandardMaterial({color:0xff632e,roughness:.8});
 const textures:T.Texture[]=[];if(quality==='high'){const texCanvas=document.createElement('canvas');texCanvas.width=texCanvas.height=128;const tc=texCanvas.getContext('2d')!,pixels=tc.createImageData(128,128);for(let i=0;i<pixels.data.length;i+=4){const v=180+Math.random()*75;pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=v;pixels.data[i+3]=255}tc.putImageData(pixels,0,0);const texture=new T.CanvasTexture(texCanvas);texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.repeat.set(180,180);snow.bumpMap=texture;snow.bumpScale=.035;textures.push(texture)}
 const ground=new T.Mesh(new T.PlaneGeometry(5000,5000),snow);ground.rotation.x=-Math.PI/2;ground.position.y=-.25;ground.receiveShadow=settings.shadows;scene.add(ground);
 const trackGeom=new T.PlaneGeometry(29,1800,1,160);trackGeom.rotateX(-Math.PI/2);const track=new T.Mesh(trackGeom,ice);track.position.y=-.13;scene.add(track);
 const leaves:T.BufferGeometry[]=[],caps:T.BufferGeometry[]=[];for(let j=0;j<settings.layers;j++){const f=j/settings.layers;let g=new T.ConeGeometry(3*(1-f*.82),quality==='low'?5:2.9,settings.segments,quality==='high'?3:1);if(quality==='high'){const a=g.attributes.position;for(let k=0;k<a.count;k++){const v=.9+.12*Math.sin(k*8.73+j);a.setX(k,a.getX(k)*v);a.setZ(k,a.getZ(k)*v)}g.computeVertexNormals()}g.translate(0,3+f*6,0);leaves.push(g);let c=new T.ConeGeometry(2.55*(1-f*.82),quality==='low'?3.5:1.5,settings.segments);c.translate(0,4+f*6,0);caps.push(c)}const leafGeometry=mergeGeometries(leaves)!,capGeometry=mergeGeometries(caps)!;leaves.concat(caps).forEach(g=>g.dispose());
 function tree(scale=1){const g=new T.Group();g.add(new T.Mesh(leafGeometry,dark),new T.Mesh(capGeometry,snow));if(quality!=='low'){const trunk=new T.Mesh(new T.CylinderGeometry(.15,.38,6,settings.segments),new T.MeshStandardMaterial({color:0x60442f,roughness:1}));trunk.position.y=3;g.add(trunk)}g.scale.setScalar(scale);g.traverse(o=>{if(o instanceof T.Mesh)o.castShadow=settings.shadows});return g}
 const forest=new T.InstancedMesh(leafGeometry,dark,130),forestSnow=new T.InstancedMesh(capGeometry,snow,130);forest.frustumCulled=false;forestSnow.frustumCulled=false;scene.add(forest,forestSnow);const dummy=new T.Object3D();
 const obstacleMeshes=objects.map(o=>{let m:T.Object3D;if(o.type==='tree')m=tree(.9);else if(o.type==='rock'){m=new T.Mesh(new T.DodecahedronGeometry(1.65,quality==='high'?2:quality==='medium'?1:0),rock);m.scale.set(1.4,.9,1);m.position.y=1}else{let g=new T.Group();let ramp=new T.Mesh(new T.BoxGeometry(7, .35,9),orange);ramp.rotation.x=.19;ramp.position.y=.9;g.add(ramp);for(let k=-1;k<=1;k++){let strip=new T.Mesh(new T.BoxGeometry(.22,.05,7),snow);strip.position.set(k*1.15,1.13,0);strip.rotation.x=.19;g.add(strip)}m=g}m.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=settings.shadows;o.receiveShadow=settings.shadows}});m.position.x=terrain(o.s)+o.x;m.position.z=-o.s;scene.add(m);return m});
 const mountains:T.Object3D[]=[];for(let i=0;i<15;i++){let m=new T.Mesh(new T.ConeGeometry(190+(i%3)*90,200+(i%5)*75,5),i%3===0?ice:snow);m.rotation.y=i*1.7;scene.add(m);mountains.push(m)}
 const finish=new T.Group();for(const x of [-14,14]){let m=new T.Mesh(new T.CylinderGeometry(.25,.25,10,6),orange);m.position.set(x,5,0);finish.add(m)}let bar=new T.Mesh(new T.BoxGeometry(28,1.5,.4),orange);bar.position.y=9;finish.add(bar);finish.position.set(terrain(7200),0,-7200);scene.add(finish);
 const skis=new T.Group();for(let x of [-.28,.28]){let ski=new T.Mesh(new T.BoxGeometry(.13,.045,1.8),orange);ski.position.set(x,-.84,-1.05);skis.add(ski)}camera.add(skis);scene.add(camera);
 const opponents=createOpponents(scene,canvas,quality);const sparksGeom=new T.BufferGeometry();const sparkData=new Float32Array(60*3);sparksGeom.setAttribute('position',new T.BufferAttribute(sparkData,3));const sparks=new T.Points(sparksGeom,new T.PointsMaterial({color:0xffffff,size:.13,transparent:true}));camera.add(sparks);
 const broken=new Set<number>(),seen=new Map<string,number>(),particles:any[]=[];const fragmentGeometry=new T.DodecahedronGeometry(1,0),fragmentMaterials=[rock,new T.MeshStandardMaterial({color:0x73503a,roughness:1}),snow];
 const fragmentMesh=new T.InstancedMesh(fragmentGeometry,new T.MeshStandardMaterial({roughness:1}),settings.debris*6);fragmentMesh.instanceMatrix.setUsage(T.DynamicDrawUsage);fragmentMesh.frustumCulled=false;fragmentMesh.count=0;scene.add(fragmentMesh);
 const flakesGeo=new T.BufferGeometry(),flakesPos=new Float32Array(settings.flakes*3);flakesGeo.setAttribute('position',new T.BufferAttribute(flakesPos,3));const flakeCanvas=document.createElement('canvas');flakeCanvas.width=32;flakeCanvas.height=32;const fc=flakeCanvas.getContext('2d')!;const gradient=fc.createRadialGradient(16,16,0,16,16,16);gradient.addColorStop(0,'rgba(255,255,255,1)');gradient.addColorStop(.35,'rgba(255,255,255,.7)');gradient.addColorStop(1,'rgba(255,255,255,0)');fc.fillStyle=gradient;fc.fillRect(0,0,32,32);const flakeTexture=new T.CanvasTexture(flakeCanvas);const snowfall=new T.Points(flakesGeo,new T.PointsMaterial({map:flakeTexture,color:0xffffff,size:quality==='high'?.16:.12,transparent:true,depthWrite:false,opacity:.85}));snowfall.frustumCulled=false;scene.add(snowfall);
 let lastVisual=performance.now();
 function impacts(racers:any[]){for(const p of racers){if(!p.impactSeq||seen.get(p.id)===p.impactSeq)continue;seen.set(p.id,p.impactSeq);const o=objects.find(x=>x.id===p.impactId);if(!o)continue;broken.add(o.id);if(Math.abs(o.s-racers[0].s)>160)continue;for(let i=0;i<settings.debris;i++){if(particles.length>=settings.debris*6)particles.shift();particles.push({x:terrain(o.s)+o.x,y:o.type==='tree'?1+Math.random()*5:1,z:-o.s,vx:(Math.random()-.5)*12,vy:3+Math.random()*9,vz:(Math.random()-.5)*16,life:1.7+Math.random(),size:.1+Math.random()*.45,color:fragmentMaterials[i%3===0?2:o.type==='tree'?1:0].color,spin:Math.random()*6})}}}
 let lastW=0,lastH=0,frames=0,perfStart=performance.now();let reduced=false,lastForestCell=NaN;
 function draw(p:any,others:any[],time:number,menu=false,intro=0){const nowVisual=performance.now(),visualDt=Math.min(.05,(nowVisual-lastVisual)/1000);lastVisual=nowVisual;impacts([p,...others]);let w=canvas.clientWidth,h=canvas.clientHeight;if(w!==lastW||h!==lastH){lastW=w;lastH=h;gl.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}const s=p.s;ground.position.z=-s;let arr=trackGeom.attributes.position;for(let i=0;i<arr.count;i++){let z=(i>>1)*1800/160-150;arr.setXYZ(i,(i%2?14.5:-14.5)+terrain(s+z),0,-s-z)}arr.needsUpdate=true;trackGeom.computeBoundingSphere();const forestCell=Math.floor((s-70)/38);if(forestCell!==lastForestCell){lastForestCell=forestCell;for(let i=0;i<130;i++){let z=forestCell*38+(i>>1)*38;dummy.position.set(terrain(z)+(i%2?1:-1)*(22+(i*17%65)),0,-z);dummy.scale.setScalar(.7+(i%7)*.16);dummy.updateMatrix();forest.setMatrixAt(i,dummy.matrix);forestSnow.setMatrixAt(i,dummy.matrix)}forest.instanceMatrix.needsUpdate=true;forestSnow.instanceMatrix.needsUpdate=true;}obstacleMeshes.forEach((m,i)=>{m.visible=!broken.has(objects[i].id)&&objects[i].s>s-30&&objects[i].s<s+1300});mountains.forEach((m,i)=>m.position.set((i-7)*220,-70,-s-1450-Math.abs(i-7)*30));let air=p.air>0?Math.sin((1-p.air/1.55)*Math.PI)*6:0;const opening=introCamera(p,others,camera.aspect);camera.position.set(terrain(s)+p.x+(opening.x-p.x)*intro,2.2+air+intro*1.3,-s+1+intro*opening.back);camera.rotation.set(0,0,0);camera.rotation.x=-.035+(opening.pitch+.035)*intro;camera.rotation.z=-p.steer*.07;const elapsed=time-p.flipAt;if(p.flipped&&elapsed>=0&&elapsed<.7&&p.air>0)camera.rotation.x+=Math.PI*2*(elapsed/.7);camera.fov=72+(p.tier-1)*1.6;camera.updateProjectionMatrix();skis.rotation.z=Math.sin(time*4)*.025;skis.visible=!menu&&intro<.05;
 opponents.update(p,others,camera,time,visualDt,menu);
 sparks.visible=p.hit>0||p.boost>0;if(sparks.visible){for(let i=0;i<60;i++){sparkData[i*3]=Math.sin(i*41+time*12)*1.8;sparkData[i*3+1]=Math.cos(i*27+time*8);sparkData[i*3+2]=-1-(i%12)/4}sparksGeom.attributes.position.needsUpdate=true}if(settings.shadows){light.position.set(terrain(s)-45,100,-s+40);light.target.position.set(terrain(s),0,-s-20)}
 for(let i=particles.length-1;i>=0;i--){const a=particles[i];a.life-=visualDt;if(a.life<=0){particles.splice(i,1);continue}a.vy-=15*visualDt;a.x+=a.vx*visualDt;a.y+=a.vy*visualDt;a.z+=a.vz*visualDt;if(a.y<.1){a.y=.1;a.vy=Math.abs(a.vy)*.3;a.vx*=.9;a.vz*=.9}}
 particles.forEach((a,i)=>{dummy.position.set(a.x,a.y,a.z);dummy.rotation.set(a.spin+a.life*2,a.life*3,0);dummy.scale.setScalar(a.size*Math.min(1,a.life*2));dummy.updateMatrix();fragmentMesh.setMatrixAt(i,dummy.matrix);fragmentMesh.setColorAt(i,a.color)});fragmentMesh.count=particles.length;fragmentMesh.instanceMatrix.needsUpdate=true;if(fragmentMesh.instanceColor)fragmentMesh.instanceColor.needsUpdate=true;dummy.rotation.set(0,0,0);
 for(let i=0;i<settings.flakes;i++){flakesPos[i*3]=camera.position.x+Math.sin(i*12.43)*26+Math.sin(nowVisual*.0003+i)*2;flakesPos[i*3+1]=((i*.37-nowVisual*.0015)%16+16)%16;flakesPos[i*3+2]=camera.position.z-((i*7.13+nowVisual*.004)%85)}flakesGeo.attributes.position.needsUpdate=true;gl.render(scene,camera);frames++;if(time>0&&performance.now()-perfStart>4000){if(frames/(performance.now()-perfStart)*1000<38&&!reduced){gl.setPixelRatio(1);gl.setSize(w,h,false);reduced=true}frames=0;perfStart=performance.now()}}
 return {draw,destroy(){opponents.destroy();textures.forEach(t=>t.dispose());fragmentMaterials.forEach(m=>m.dispose());flakeTexture.dispose();scene.traverse(o=>{const m=o as T.Mesh;if(m.geometry)m.geometry.dispose();if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>x.dispose())});gl.dispose()}};
}
