import {build} from 'esbuild';import assert from 'node:assert/strict';
const output=await build({entryPoints:['multiplayer/worker.mjs'],bundle:true,write:false,format:'cjs',external:['cloudflare:workers']});let module={exports:{}};new Function('require','module','exports',output.outputFiles[0].text)(()=>({DurableObject:class{}}),module,module.exports);const worker=module.exports.default;
const key=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const jwk=await crypto.subtle.exportKey('jwk',key.publicKey);jwk.kid='routing';const b64=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const data=b64({alg:'RS256',kid:'routing'})+'.'+b64({iss:'https://routing.cloudflareaccess.com',aud:['aud'],sub:'real-owner',email:'owner@example.com',exp:Math.floor(Date.now()/1000)+600});const jwt=data+'.'+Buffer.from(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key.privateKey,new TextEncoder().encode(data))).toString('base64url');
let forwarded,options,calls=0;const env={JOIN_LIMIT:{limit:async()=>({success:true})},HOST_CREATE_LIMIT:{limit:async()=>({success:true})},ACCESS_TEAM_DOMAIN:'routing.cloudflareaccess.com',ACCESS_AUD:'aud',DO_LOCATION_HINT:'apac',CF_ZONE_NAME:'example.com',ROOMS:{idFromName:n=>n,get:(id,opts)=>{options=opts;return{fetch:async r=>{calls++;forwarded=r;return Response.json({ok:true})}}}},ASSETS:{fetch:async()=>new Response('game')}};const req=(path,headers={})=>new Request('https://ski.example.com'+path,{method:path.endsWith('/create')||path.endsWith('/close')?'POST':'GET',headers});
assert.equal((await worker.fetch(req('/api/rooms/ABC123/create'),env)).status,403);assert.equal(calls,0);assert.equal((await worker.fetch(req('/api/rooms/ABC123?host=stolen'),env)).status,403);assert.equal((await worker.fetch(req('/host/api/rooms/ABC123/create'),env)).status,401);assert.equal(calls,0);
await worker.fetch(req('/api/rooms/ABC123?ticket=00000000-0000-0000-0000-000000000001',{Upgrade:'websocket','X-Skigpt-Owner':'forged','X-Skigpt-Location':'forged'}),env);assert.equal(forwarded.headers.get('X-Skigpt-Owner'),null);assert.equal(forwarded.headers.get('X-Skigpt-Location'),null);
const oldFetch=globalThis.fetch;globalThis.fetch=async()=>Response.json({keys:[jwk]});try{const r=req('/host/api/rooms/ABC123/create',{'Cf-Access-Jwt-Assertion':jwt,'X-Skigpt-Owner':'forged'});Object.defineProperty(r,'cf',{value:{colo:'TPE',country:'TW',region:'Taipei'}});assert.equal((await worker.fetch(r,env)).status,200);assert.equal(forwarded.headers.get('X-Skigpt-Owner'),'real-owner');const location=JSON.parse(forwarded.headers.get('X-Skigpt-Location'));assert.equal(location.ingressColo,'TPE');assert.equal(location.actualDoRegion,null);assert.equal(location.zoneSource,'configured');assert.equal(options.locationHint,'apac');assert.equal((await worker.fetch(req('/host',{'Cf-Access-Jwt-Assertion':jwt}),env)).headers.get('Cache-Control'),'private, no-store')}finally{globalThis.fetch=oldFetch}
console.log('PASS protected routing, fail-closed create, public joining, forged-header stripping, real JWT authentication and truthful location metadata.');

const before=calls;
assert.equal((await worker.fetch(req('/api/rooms/ABC123'),env)).status,426);
assert.equal((await worker.fetch(req('/api/rooms/ABC123?id='+('x'.repeat(1000)),{Upgrade:'websocket'}),env)).status,400);
assert.equal((await worker.fetch(req('/api/rooms/ABC123?ticket=00000000-0000-0000-0000-000000000001',{Upgrade:'websocket'}),{...env,JOIN_LIMIT:{limit:async()=>({success:false})}})).status,429);
assert.equal((await worker.fetch(req('/api/rooms/ABC123?ticket=00000000-0000-0000-0000-000000000001',{Upgrade:'websocket'}),{...env,JOIN_LIMIT:null})).status,503);
assert.equal(calls,before,'invalid or limited request never invokes DO');
console.log('PASS edge rate-limit and fail-closed binding checks.');

const guarded=await worker.fetch(req('/'),env);assert.match(guarded.headers.get('Content-Security-Policy'),/frame-ancestors 'none'/);assert.match(guarded.headers.get('Content-Security-Policy'),/wss:\/\/ski.example.com/);assert.equal(guarded.headers.get('X-Content-Type-Options'),'nosniff');assert.equal(guarded.headers.get('Referrer-Policy'),'no-referrer');
const callsBefore=calls;assert.equal((await worker.fetch(req('/api/rooms/ABC123?resume=secret',{Upgrade:'websocket'}),env)).status,400);assert.equal((await worker.fetch(req('/api/rooms/ABC123?id=old',{Upgrade:'websocket'}),env)).status,400);assert.equal(calls,callsBefore);console.log('PASS security headers and legacy credential URL rejection');

const ticketPath='/api/rooms/ABC123/ticket';const ticketReq=new Request('https://ski.example.com'+ticketPath,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:'player',name:'P'})});const ticketResponse=await worker.fetch(ticketReq,env);assert.equal(ticketResponse.status,200);assert.equal(ticketResponse.headers.get('Cache-Control'),'no-store');assert.equal(forwarded.url,'https://ski.example.com'+ticketPath);assert.equal((await worker.fetch(new Request('https://ski.example.com'+ticketPath,{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:'{}'}),env)).status,403);assert.equal((await worker.fetch(new Request('https://ski.example.com/host/api/rooms/ABC123/ticket',{method:'POST'}),env)).status,401);
