import {test} from 'node:test';import assert from 'node:assert/strict';import {MotionControls,portraitRoll} from '../game/motion.mjs';import {racer,step,course} from '../game/physics.mjs';
test('upright Euler branch change preserves steering direction',()=>{assert.ok(Math.abs(portraitRoll(85,40)-portraitRoll(95,-40))<1e-10);assert.equal(portraitRoll(90,0),0);assert.equal(portraitRoll(null,3),null)});
test('calibration dead zone and return to neutral',()=>{let m=new MotionControls();m.orientation({beta:65,gamma:0},1);for(let t=20;t<500;t+=20)m.orientation({beta:65,gamma:30},t);assert.ok(m.steer>.4);for(let t=500;t<1200;t+=20)m.orientation({beta:65,gamma:0},t);assert.equal(m.steer,0)});
test('moderate forward/up toss is accepted without positive Y restriction',()=>{let m=new MotionControls();assert.equal(m.motion({acceleration:{x:0,y:-4,z:5}},100),false);assert.equal(m.motion({acceleration:{x:0,y:-4,z:5}},120),true);assert.equal(m.motion({acceleration:{x:0,y:-4,z:5}},140),false)});
test('missing linear acceleration falls back to gravity-inclusive stream',()=>{let m=new MotionControls();m.motion({acceleration:null,accelerationIncludingGravity:{x:0,y:9.8,z:0}},100);m.motion({acceleration:null,accelerationIncludingGravity:{x:0,y:16.8,z:3}},120);assert.equal(m.motion({acceleration:null,accelerationIncludingGravity:{x:0,y:16.8,z:3}},140),true)});
test('single tap spike is rejected, pitch fallback works without motion',()=>{let m=new MotionControls();assert.equal(m.motion({acceleration:{x:0,y:12,z:0}},100),false);assert.equal(m.motion({acceleration:{x:0,y:0,z:0}},120),false);let n=new MotionControls();n.orientation({beta:60,gamma:0},1000);assert.equal(n.orientation({beta:81,gamma:0},1120),true)});
test('gesture just before ramp survives until liftoff',()=>{let p=racer('x','x');p.speed=22;step(p,{tap:true,shake:true},.05,1,[{id:1,s:4,x:0,type:'ramp'}]);assert.equal(p.tier,2);for(let n=0;n<4;n++)step(p,{tap:true},.05,1.05+n*.05,[{id:1,s:4,x:0,type:'ramp'}]);assert.equal(p.tier,3);assert.equal(p.flipped,true)});
test('stale gesture cannot trigger a distant ramp',()=>{let p=racer('x','x');p.speed=22;let objects=[{id:1,s:40,x:0,type:'ramp'}];step(p,{tap:true,shake:true},.05,0,objects);for(let n=0;n<40;n++)step(p,{tap:true},.05,.05+n*.05,objects);assert.equal(p.tier,2)});
test('complete seeded course reaches nine using motion through real ramp crossings',()=>{let p=racer('x','x'),objects=course(7),motion=new MotionControls();let lastRamp=-1;for(let frame=0;frame<36000&&!p.finished;frame++){let t=frame/60;let ramp=objects.find(o=>o.type==='ramp'&&o.s>p.s);let shake=false;if(ramp&&ramp.s-p.s<Math.max(2,p.speed*.2)&&ramp.id!==lastRamp){motion.motion({acceleration:{x:0,y:-4,z:5}},t*1000);shake=motion.motion({acceleration:{x:0,y:-4,z:5}},t*1000+16);if(shake)lastRamp=ramp.id}step(p,{tap:true,steer:(ramp?.x||0)/12,shake},1/60,t,objects)}assert.equal(p.tier,9);assert.ok(p.finished>0);assert.ok(p.speed>22*8);console.log('Seed 7 course finish:',p.finished.toFixed(2),'seconds, tier',p.tier)});
