import {build} from 'esbuild';import assert from 'node:assert/strict';
const output=await build({entryPoints:['multiplayer/worker.mjs'],bundle:true,write:false,format:'cjs',external:['cloudflare:workers']});
class Socket{constructor(){this.messages=[]}serializeAttachment(x){this.a=structuredClone(x)}deserializeAttachment(){return structuredClone(this.a)}send(x){this.messages.push(JSON.parse(x))}close(){this.closed=true}}
class Pair{constructor(){this[0]=new Socket();this[1]=new Socket()}}
class Resp{constructor(body,opts={}){Object.assign(this,{status:200,body},opts)}static json(x,opts={}){return new Resp(JSON.stringify(x),opts)}async json(){return JSON.parse(this.body)}}
let module={exports:{}};new Function('require','module','exports','WebSocketPair','Response',output.outputFiles[0].text)(()=>({DurableObject:class{}}),module,module.exports,Pair,Resp);const {RaceRoom:Room,LIMITS}=module.exports;
let now=1800000000000;const realNow=Date.now;Date.now=()=>now;
async function setup(){const sockets=[],saved=new Map();let ready,alarmAt=null,writes=0;const ctx={id:{toString:()=> 'test-object'},storage:{get:async k=>saved.get(k),put:async(k,v)=>{writes++;saved.set(k,structuredClone(v))},setAlarm:async t=>alarmAt=t,deleteAlarm:async()=>alarmAt=null,deleteAll:async()=>saved.clear()},blockConcurrencyWhile:f=>ready=f(),acceptWebSocket:w=>sockets.push(w),getWebSockets:()=>sockets};const room=new Room(ctx,{});await ready;const request=(suffix,headers={})=>new Request('http://localhost/api/rooms/ABC123'+suffix,{headers:{'X-Skigpt-Owner':'host-sub','X-Skigpt-Email':'host@example.com','X-Skigpt-Access-Exp':String(Math.floor(now/1000)+3600),...headers}});let res=await room.fetch(request('/create'));const {token}=await res.json();await room.fetch(request('?host='+token,{Upgrade:'websocket'}));const host=sockets.at(-1);await room.fetch(request('?id=p1&name=Alice',{Upgrade:'websocket'}));const a=sockets.at(-1);await room.fetch(request('?id=p2&name=Bob',{Upgrade:'websocket'}));const b=sockets.at(-1);return {room,host,a,b,token,saved,ctx,sockets,request,alarm:()=>alarmAt,writes:()=>writes}}
try{
const t=await setup();await t.room.webSocketClose(t.host);const due=t.alarm(),resume=t.room.state.players.find(p=>p.id==='p1').resume;
for(let i=0;i<5;i++){now+=10000;assert.equal((await t.room.fetch(t.request('?id=p1&resume='+resume,{Upgrade:'websocket'}))).status,101);assert.equal(t.alarm(),due,'reconnect never postpones cleanup')}
now+=10001;assert.equal((await t.room.fetch(t.request('?id=p1&resume='+resume,{Upgrade:'websocket'}))).status,410);assert.equal(t.room.state,null);assert.equal(t.alarm(),null);
const ttl=await setup();ttl.room.state.created=now-LIMITS.lifetime;await ttl.room.webSocketMessage(ttl.a,JSON.stringify({type:'pong',nonce:'test'}));assert.equal(ttl.room.state,null,'message enforces TTL even before alarm');assert.equal(ttl.saved.size,0);
const fetchTTL=await setup();fetchTTL.room.state.created=now-LIMITS.lifetime;assert.equal((await fetchTTL.room.fetch(fetchTTL.request('?id=new',{Upgrade:'websocket'}))).status,410);
const empty=await setup();await empty.room.webSocketMessage(empty.host,JSON.stringify({type:'start'}));await empty.room.webSocketClose(empty.a);await empty.room.webSocketClose(empty.b);now+=LIMITS.emptyRace+1;assert.equal((await empty.room.fetch(empty.request('?id=p1&resume='+empty.room.state.players[0].resume,{Upgrade:'websocket'}))).status,410);
const normal=await setup();for(let i=0;i<14;i++)assert.equal((await normal.room.fetch(normal.request('?id=n'+i,{Upgrade:'websocket'}))).status,101);const humans=normal.room.sockets().filter(w=>!w.deserializeAttachment().host);assert.equal(humans.length,16);await normal.room.webSocketMessage(normal.host,JSON.stringify({type:'start'}));
for(let i=0;i<200;i++){now+=50;await Promise.all(humans.map(w=>normal.room.webSocketMessage(w,JSON.stringify({type:'input',steer:0,tap:true,shake:false}))));if(now>=normal.alarm())await normal.room.alarm()}
assert.ok(humans.every(w=>!w.closed),'16 simultaneous 20Hz players remain connected');
const burst=await setup();const startRx=burst.room.state.stats.rx;for(let i=0;i<200;i++)await burst.room.webSocketMessage(burst.a,JSON.stringify({type:'input',steer:0,tap:true,shake:false}));assert.ok(burst.a.closed);assert.ok(burst.room.state.stats.rx-startRx<=80);assert.ok(!burst.b.closed);
const invalid=await setup();await invalid.room.webSocketMessage(invalid.a,'null');assert.ok(invalid.a.closed);assert.ok(!invalid.b.closed);assert.equal((await invalid.room.fetch(invalid.request('?id='+('x'.repeat(1000)),{Upgrade:'websocket'}))).status,400);
const joins=await setup();for(let i=0;i<50;i++)await joins.room.fetch(joins.request('?id=p1&resume=wrong',{Upgrade:'websocket'}));assert.equal((await joins.room.fetch(joins.request('?id=new',{Upgrade:'websocket'}))).status,429);
console.log('PASS High fixes: non-postponable alarm, host grace, fetch/message TTL, empty deadline, 16 players at 20Hz, flood disconnect, schema rejection and room join budget.');
}finally{Date.now=realNow}
