import {build} from 'esbuild';import assert from 'node:assert/strict';
const output=await build({entryPoints:['multiplayer/worker.mjs'],bundle:true,write:false,format:'cjs',external:['cloudflare:workers']});
class Socket{constructor(){this.messages=[]}serializeAttachment(x){this.a=structuredClone(x)}deserializeAttachment(){return structuredClone(this.a)}send(x){this.messages.push(JSON.parse(x))}close(){this.closed=true}}
class Pair{constructor(){this[0]=new Socket();this[1]=new Socket()}}
class Resp{constructor(body,opts={}){Object.assign(this,{status:200,body},opts)}static json(x,opts={}){return new Resp(JSON.stringify(x),opts)}async json(){return JSON.parse(this.body)}}
let module={exports:{}};new Function('require','module','exports','WebSocketPair','Response',output.outputFiles[0].text)(()=>({DurableObject:class{}}),module,module.exports,Pair,Resp);const {RaceRoom:Room,LIMITS}=module.exports;
let now=1800000000000;const realNow=Date.now;Date.now=()=>now;
async function setup(){const sockets=[],saved=new Map();let ready,alarmAt=null,writes=0;const ctx={id:{toString:()=> 'test-object'},storage:{get:async k=>saved.get(k),put:async(k,v)=>{writes++;saved.set(k,structuredClone(v))},setAlarm:async t=>alarmAt=t,deleteAlarm:async()=>alarmAt=null,deleteAll:async()=>saved.clear()},blockConcurrencyWhile:f=>ready=f(),acceptWebSocket:w=>sockets.push(w),getWebSockets:()=>sockets};const room=new Room(ctx,{});await ready;const request=(suffix,headers={})=>new Request('http://localhost/api/rooms/ABC123'+suffix,{headers:{'X-Skigpt-Owner':'host-sub','X-Skigpt-Email':'host@example.com','X-Skigpt-Access-Exp':String(Math.floor(now/1000)+3600),...headers}});let res=await room.fetch(request('/create'));const {token}=await res.json();await room.fetch(request('?host='+token,{Upgrade:'websocket'}));const host=sockets.at(-1);await room.fetch(request('?id=p1&name=Alice',{Upgrade:'websocket'}));const a=sockets.at(-1);await room.fetch(request('?id=p2&name=Bob',{Upgrade:'websocket'}));const b=sockets.at(-1);return {room,host,a,b,token,saved,ctx,sockets,request,alarm:()=>alarmAt,writes:()=>writes}}
try{
const t=await setup();await t.room.webSocketClose(t.b);const offline=t.room.state.players.find(p=>p.id==='p2');assert.equal(offline.offlineAt,now);assert.ok(!('offlineAt' in t.room.snapshot().players[0]));
now+=3000;assert.equal((await t.room.fetch(t.request('?id=p2&resume='+offline.resume,{Upgrade:'websocket'}))).status,101);const replacement=t.sockets.at(-1);await t.room.webSocketClose(t.b);assert.equal(t.room.state.players.find(p=>p.id==='p2').offlineAt,undefined,'old close does not mark replacement offline');await t.room.webSocketClose(replacement);now+=LIMITS.seatGrace;await t.room.alarm();assert.ok(!t.room.state.players.some(p=>p.id==='p2'));assert.ok(!t.saved.get('room').players.some(p=>p.id==='p2'),'reclaimed state persisted');assert.ok(t.room.state,'seat expiry does not close room');
const full=await setup();for(let i=3;i<=16;i++)assert.equal((await full.room.fetch(full.request('?id=p'+i,{Upgrade:'websocket'}))).status,101);await full.room.webSocketClose(full.b);assert.equal((await full.room.fetch(full.request('?id=new',{Upgrade:'websocket'}))).status,429);now+=LIMITS.seatGrace;assert.equal((await full.room.fetch(full.request('?id=new',{Upgrade:'websocket'}))).status,101,'join reclaims even before alarm');assert.equal(full.room.state.players.filter(p=>!p.ai).length,16);
const ai=await setup();for(const w of ai.sockets.filter(w=>!w.deserializeAttachment().host&&w!==ai.a))await ai.room.webSocketClose(w);for(let i=3;i<=15;i++){await ai.room.fetch(ai.request('?id=p'+i,{Upgrade:'websocket'}));await ai.room.webSocketClose(ai.sockets.at(-1))}assert.equal(ai.room.state.players.length,16);assert.equal((await ai.room.fetch(ai.request('?id=last',{Upgrade:'websocket'}))).status,101,'AI is not a human seat');
const stale=await setup();now+=LIMITS.stale+1;for(const w of [stale.host,stale.a])w.serializeAttachment({...w.deserializeAttachment(),seen:now});await stale.room.alarm();assert.ok(stale.b.closed);assert.equal(stale.room.state.players.find(p=>p.id==='p2').offlineAt,now);now+=LIMITS.seatGrace;for(const w of [stale.host,stale.a])w.serializeAttachment({...w.deserializeAttachment(),seen:now});await stale.room.alarm();assert.ok(!stale.room.state.players.some(p=>p.id==='p2'));
const race=await setup();await race.room.webSocketMessage(race.host,JSON.stringify({type:'start'}));race.room.state.players.find(p=>p.id==='p2').finished=123;await race.room.webSocketClose(race.b);now+=LIMITS.seatGrace;await race.room.alarm();assert.equal(race.room.state.players.find(p=>p.id==='p2').finished,123);race.room.state.phase='results';await race.room.webSocketMessage(race.host,JSON.stringify({type:'reset'}));assert.equal(race.room.state.players.find(p=>p.id==='p2').offlineAt,now);now+=LIMITS.seatGrace;for(const w of [race.host,race.a])w.serializeAttachment({...w.deserializeAttachment(),seen:now});await race.room.alarm();assert.ok(!race.room.state.players.some(p=>p.id==='p2'));
let touched=false;const env=new Proxy({},{get(){touched=true;throw Error('must not reach bindings')}});for(const host of ['skigpt.account.workers.dev','abc-skigpt.account.workers.dev'])for(const path of ['/host','/api/rooms/ABC123'])assert.equal((await module.exports.default.fetch(new Request('https://'+host+path),env)).status,403);assert.equal(touched,false);
const {readFileSync}=await import('node:fs');const config=readFileSync('wrangler.jsonc','utf8');assert.match(config,/"workers_dev"\s*:\s*false/);assert.match(config,/"preview_urls"\s*:\s*false/);
console.log('PASS: lobby grace, reconnect, old close, alarm and join reclamation, persistence, AI capacity, heartbeat timeout, race/results retention, reset cleanup, alternate-host denial and deployment flags');
}finally{Date.now=realNow}
