const cache=new Map();
const bytes=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
const decode=s=>JSON.parse(new TextDecoder().decode(bytes(s)));
export function accessConfig(env){const domain=String(env.ACCESS_TEAM_DOMAIN||'').replace(/^https:\/\//,'').replace(/\/$/,'');if(!/^[a-z0-9-]+\.cloudflareaccess\.com$/i.test(domain)||!env.ACCESS_AUD)return null;return {issuer:`https://${domain}`,aud:String(env.ACCESS_AUD)}}
export async function verifyAccess(request,env,fetchKeys=fetch){const config=accessConfig(env);if(!config)throw Object.assign(new Error('尚未設定 ACCESS_TEAM_DOMAIN 與 ACCESS_AUD，開房功能已鎖定。'),{status:503});
 const token=request.headers.get('Cf-Access-Jwt-Assertion')||request.headers.get('Cookie')?.match(/(?:^|;\s*)CF_Authorization=([^;]+)/)?.[1];if(!token||token.length>16000)throw Object.assign(new Error('請先通過 Cloudflare Access 登入。'),{status:401});
 try{const parts=token.split('.');if(parts.length!==3)throw Error();const head=decode(parts[0]),claims=decode(parts[1]),now=Math.floor(Date.now()/1000);if(head.alg!=='RS256'||typeof head.kid!=='string'||claims.iss!==config.issuer||!(Array.isArray(claims.aud)?claims.aud:[claims.aud]).includes(config.aud)||!Number.isFinite(claims.exp)||claims.exp<=now||(claims.nbf!=null&&(!Number.isFinite(claims.nbf)||claims.nbf>now+30))||typeof claims.sub!=='string'||!claims.sub||typeof claims.email!=='string'||!claims.email)throw Error();
 let entry=cache.get(config.issuer);if(!entry||entry.until<Date.now()){const res=await fetchKeys(config.issuer+'/cdn-cgi/access/certs',{signal:AbortSignal.timeout(5000)});if(!res.ok)throw Error();const data=await res.json();if(!Array.isArray(data.keys))throw Error();entry={keys:data.keys,until:Date.now()+300000};cache.set(config.issuer,entry)}
 const jwk=entry.keys.find(k=>k.kid===head.kid&&k.kty==='RSA');if(!jwk)throw Error();const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);if(!await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,bytes(parts[2]),new TextEncoder().encode(parts[0]+'.'+parts[1])))throw Error();return {sub:claims.sub,email:claims.email,exp:claims.exp};
 }catch{throw Object.assign(new Error('Access 驗證失敗或已過期，請重新登入。'),{status:403})}}
