import {secureResponse,readTicketBody,ticketHash} from './security.mjs';
import { DurableObject } from 'cloudflare:workers';
import {take,validJoin,message,edgeLimit} from './limits.mjs';
import {verifyAccess} from './access.mjs';
import {gridX} from '../game/opponent-view.mjs';
import {AI_ID,companion,aiInput} from '../game/ai.mjs';
import {course,racer,step,MAX_PLAYERS} from '../game/physics.mjs';
export const LIMITS={seatGrace:30000,heartbeat:15000,stale:45000,hostGrace:60000,emptyRace:30000,idle:300000,lifetime:3600000,checkpoint:2000};
export class RaceRoom extends DurableObject{
 constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.state=null;this.queue=Promise.resolve();this.last=Date.now();this.lastSave=0;this.nextAlarm=null;this.pendingMessages=0;this.messageBudget={};ctx.blockConcurrencyWhile(async()=>{this.state=await ctx.storage.get('room')||null;this.nextAlarm=await ctx.storage.getAlarm?.()??null;this.last=this.state?.lastTick||Date.now();if(this.state){this.state.stats??={rx:0,tx:0,bytes:0,ticks:0,writes:0};this.state.activity??=this.state.created;this.state.hostMissing??=Date.now();for(const w of ctx.getWebSockets()){const a=w.deserializeAttachment();if(a&&a.seen==null)w.serializeAttachment({...a,seen:Date.now(),pingAt:0})}}})}
 run(action){const task=this.queue.then(action);this.queue=task.catch(()=>{});return task}
 fetch(req){return this.run(()=>this.handleFetch(req))}
 webSocketMessage(ws,data){
  const a=ws.deserializeAttachment();if(!a||a.gone)return Promise.resolve();
  a.budget??={};const allowed=take(a.budget,40,80)&&take(this.messageBudget,800,1600)&&this.pendingMessages<128;const m=allowed?message(data):null;
  if(!m){a.gone=true;ws.serializeAttachment(a);ws.close(1008,'Invalid or excessive messages');return this.run(()=>this.handleClose(ws))}
  ws.serializeAttachment(a);this.pendingMessages++;
  return this.run(()=>this.handleMessage(ws,m)).finally(()=>this.pendingMessages--);
 }
 alarm(){return this.run(()=>this.handleAlarm())}
 webSocketClose(ws){return this.run(()=>this.handleClose(ws))}
 sockets(){return this.ctx.getWebSockets().filter(w=>{const a=w.deserializeAttachment();return a&&!a.gone})}
 async save(){if(!this.state||this.state.phase==='closed')return;this.lastSave=Date.now();this.state.stats.writes++;await this.ctx.storage.put('room',this.state)}
 deadline(){const s=this.state;if(!s)return Infinity;const hosts=this.sockets().filter(w=>w.deserializeAttachment().host);const hostUntil=hosts.length?Math.max(...hosts.map(w=>{const a=w.deserializeAttachment();return Math.min((a.accessExp||0)*1000,a.seen+LIMITS.stale)})):Infinity;return Math.min(s.created+LIMITS.lifetime,s.phase!=='race'?s.activity+LIMITS.idle:Infinity,s.hostMissing?s.hostMissing+LIMITS.hostGrace:hostUntil+LIMITS.hostGrace,s.emptySince?s.emptySince+LIMITS.emptyRace:Infinity)}
 async expire(){if(this.state&&Date.now()>=this.deadline()){await this.closeRoom('房間逾時自動關閉');return true}return false}
 async schedule(ms){if(!this.state||this.state.phase==='closed'||await this.expire())return;
  // Reconnect must never postpone an existing cleanup alarm.
  const next=Math.min(Date.now()+ms,this.deadline(),this.seatDeadline(),this.nextAlarm??Infinity);if(next===this.nextAlarm)return;this.nextAlarm=next;await this.ctx.storage.setAlarm(next)}

 send(w,m){try{const data=JSON.stringify(m);w.send(data);if(this.state){this.state.stats.tx++;this.state.stats.bytes+=new TextEncoder().encode(data).length}}catch{}}
 async closeRoom(reason){if(!this.state)return;this.state.phase='closed';this.nextAlarm=null;await this.ctx.storage.deleteAlarm();await this.ctx.storage.deleteAll();for(const w of this.sockets()){this.send(w,{type:'closed',reason,alarmCancelled:true,dataDeleted:true,closedAt:Date.now()});const a=w.deserializeAttachment();w.serializeAttachment({...a,gone:true});try{w.close(1000,'Room closed')}catch{}}this.state=null;console.log(JSON.stringify({event:'room_closed',reason,alarmCancelled:true,dataDeleted:true,sockets:0}))}
 async handleFetch(req){if(await this.expire())return new Response('Room expired',{status:410});const u=new URL(req.url);if(!validJoin(u))return new Response('Invalid parameters',{status:400});if(u.pathname.endsWith('/create')){if(this.state)return Response.json({error:'Room exists'},{status:409});const owner=req.headers.get('X-Skigpt-Owner');if(!owner)return new Response('Access required',{status:403});const token=crypto.randomUUID(),now=Date.now();this.state={token,owner,hostEmail:req.headers.get('X-Skigpt-Email'),location:JSON.parse(req.headers.get('X-Skigpt-Location')||'{}'),seed:crypto.getRandomValues(new Uint32Array(1))[0],phase:'lobby',start:0,players:[],created:now,activity:now,hostMissing:now,stats:{rx:0,tx:0,bytes:0,ticks:0,writes:0}};await this.save();await this.schedule(LIMITS.heartbeat);return Response.json({token})}
 if(!this.state||this.state.phase==='closed')return Response.json({error:'房間已關閉或不存在'},{status:404});
 if(u.pathname.endsWith('/close')){if(req.headers.get('X-Skigpt-Owner')!==this.state.owner||req.headers.get('Authorization')!==`Bearer ${this.state.token}`)return new Response('Forbidden',{status:403});await this.closeRoom('主控強制關房');return Response.json({closed:true,alarmCancelled:true,dataDeleted:true})}
 const budget=u.pathname.endsWith('/ticket')?'ticketBudget':'joinBudget';this.state[budget]??={};if(!take(this.state[budget],2,32))return new Response('Room join limit',{status:429});
 if(u.pathname.endsWith('/ticket')){
  let body;try{body=await readTicketBody(req)}catch{return new Response('Invalid ticket request',{status:400})}
  const host=u.pathname.startsWith('/host/');if((host&&(body.host!==this.state.token||req.headers.get('X-Skigpt-Owner')!==this.state.owner))||(!host&&body.host!==undefined))return new Response('Forbidden',{status:403});
  const p=this.state.players.find(p=>p.id===body.id);if(body.id===AI_ID||(!host&&p&&p.resume!==body.resume))return new Response('Forbidden',{status:403});
  if(!host&&!p&&this.state.phase!=='lobby')return new Response('Race started',{status:409});
  const now=Date.now();this.state.tickets=(this.state.tickets||[]).filter(t=>t.expires>now);if(this.state.tickets.length>=64)return new Response('Ticket limit',{status:429});
  const ticket=crypto.randomUUID(),expires=now+30000;this.state.tickets.push({hash:await ticketHash(ticket),expires,origin:u.origin,owner:host?this.state.owner:null,body:{...body,host:host?body.host:undefined}});await this.save();return Response.json({ticket,expires},{headers:{'Cache-Control':'no-store'}});
 }
 if(u.searchParams.has('ticket')){
  const hash=await ticketHash(u.searchParams.get('ticket')),tickets=this.state.tickets||[],entry=tickets.find(t=>t.hash===hash);
  this.state.tickets=tickets.filter(t=>t.hash!==hash&&t.expires>Date.now());await this.save();
  if(!entry||entry.expires<=Date.now()||entry.origin!==u.origin||!!entry.owner!==u.pathname.startsWith('/host/')||(entry.owner&&req.headers.get('X-Skigpt-Owner')!==entry.owner))return new Response('Invalid or expired ticket',{status:403});
  u.search='';for(const [key,value] of Object.entries(entry.body))if(value!==undefined)u.searchParams.set(key,value);
 }
 if(this.reapLobby()){this.syncCompanion();await this.save();await this.schedule(LIMITS.heartbeat);this.broadcast(true)}
 if(req.headers.get('Upgrade')!=='websocket')return new Response('WebSocket required',{status:426});if(this.sockets().length>=MAX_PLAYERS+2)return new Response('房間已滿',{status:429});const wantsHost=u.searchParams.has('host');if(wantsHost&&(req.headers.get('X-Skigpt-Owner')!==this.state.owner||u.searchParams.get('host')!==this.state.token))return new Response('Access required',{status:403});const host=wantsHost,id=u.searchParams.get('id')||crypto.randomUUID();if(id===AI_ID)return new Response('Reserved player ID',{status:403});let existing=this.state.players.find(p=>p.id===id);if(!host&&existing&&existing.resume!==u.searchParams.get('resume'))return new Response('無法恢復此玩家',{status:403});if(existing&&Date.now()-(existing.joinedAt||0)<2000)return new Response('Reconnect too soon',{status:429});if(!host&&!existing&&this.state.phase!=='lobby')return new Response('比賽已開始',{status:409});if(!host&&!existing&&this.state.players.filter(p=>!p.ai).length>=MAX_PLAYERS)return new Response('房間已滿',{status:429});
 for(const w of this.sockets()){const a=w.deserializeAttachment();if(host?a.host:!a.host&&a.id===id){w.serializeAttachment({...a,gone:true});w.close(1000,'Reconnected')}}
 const [client,server]=Object.values(new WebSocketPair());this.ctx.acceptWebSocket(server);if(!host&&!existing){existing={...racer(id,(u.searchParams.get('name')||'滑雪者').slice(0,16)),resume:crypto.randomUUID()};this.state.players.push(existing)}const now=Date.now();if(existing){existing.joinedAt=now;delete existing.offlineAt;}server.serializeAttachment({id,host,accessExp:host?Number(req.headers.get('X-Skigpt-Access-Exp')):null,last:0,seen:now,pingAt:now,pingNonce:crypto.randomUUID()});if(host)this.state.hostMissing=0;this.state.emptySince=0;this.state.activity=now;this.syncCompanion();this.send(server,{type:'welcome',id,resume:existing?.resume,host});this.send(server,{type:'ping',nonce:server.deserializeAttachment().pingNonce});await this.save();await this.schedule(this.state.phase==='race'?50:LIMITS.heartbeat);this.broadcast(true);return new Response(null,{status:101,webSocket:client})}
 // Lobby seats survive brief disconnects, but never reserve capacity indefinitely.
 seatDeadline(){return this.state?.phase==='lobby'?Math.min(Infinity,...this.state.players.filter(p=>!p.ai&&p.offlineAt!=null).map(p=>p.offlineAt+LIMITS.seatGrace)):Infinity}
 reapLobby(){if(this.state?.phase!=='lobby')return false;const now=Date.now(),online=new Set(this.sockets().filter(w=>!w.deserializeAttachment().host).map(w=>w.deserializeAttachment().id));let changed=false;this.state.players=this.state.players.filter(p=>{if(p.ai)return true;if(online.has(p.id)){if(p.offlineAt!=null){delete p.offlineAt;changed=true}return true}if(p.offlineAt==null){p.offlineAt=now;changed=true}if(now>=p.offlineAt+LIMITS.seatGrace){changed=true;return false}return true});return changed}
 syncCompanion(){if(this.state?.phase!=='lobby')return;const humans=this.sockets().filter(w=>!w.deserializeAttachment().host).length;this.state.players=this.state.players.filter(p=>!p.ai);if(humans===1)this.state.players.push(companion())}
 snapshot(){const connections=this.sockets();return {type:'state',seed:this.state.seed,phase:this.state.phase,start:this.state.start,now:Date.now(),players:this.state.players.map(({resume,joinedAt,offlineAt,...p})=>{const a=connections.find(w=>{let a=w.deserializeAttachment();return !a.host&&a.id===p.id})?.deserializeAttachment();return {...p,online:p.ai||!!a,ping:a?.rtt??null,pingAt:a?.rttAt??null}})}}
 info(){const s=this.state;return {phase:s.phase,location:{...(s.location||{}),jurisdiction:this.ctx.id?.jurisdiction||null},hostEmail:s.hostEmail||null,aiPlayers:s.players.filter(p=>p.ai).length,connections:this.sockets().length,onlinePlayers:this.sockets().filter(w=>!w.deserializeAttachment().host).length,created:s.created,expires:s.created+LIMITS.lifetime,idleDeadline:s.activity+LIMITS.idle,hostDeadline:s.hostMissing?s.hostMissing+LIMITS.hostGrace:null,nextAlarm:this.nextAlarm,tickHz:s.phase==='race'&&this.sockets().some(w=>!w.deserializeAttachment().host)?20:0,checkpointMs:LIMITS.checkpoint,...s.stats,objectId:this.ctx.id?.toString()||'local-test'}}
 broadcast(force=false){if(!this.state||this.state.phase==='closed')return;const snapshot=this.snapshot();for(const w of this.sockets()){const a=w.deserializeAttachment(),now=Date.now();if(a.host&&!force&&this.state.phase==='race'&&now-(a.dashboardAt||0)<500)continue;a.dashboardAt=now;w.serializeAttachment(a);this.send(w,a.host?{...snapshot,doInfo:this.info()}:snapshot)}}
 async handleMessage(ws,m){if(!this.state||await this.expire())return;const a=ws.deserializeAttachment();if(!a||a.gone)return;if(a.host&&(!a.accessExp||a.accessExp*1000<=Date.now())){ws.serializeAttachment({...a,gone:true});ws.close(1008,'Access expired');this.state.hostMissing||=Date.now();await this.save();return}this.state.stats.rx++;const now=Date.now();a.seen=now;ws.serializeAttachment(a);
 if(m.type==='pong'){if(m.nonce===a.pingNonce&&a.pingAt){a.rtt=now-a.pingAt;a.rttAt=now;a.pingNonce=null;ws.serializeAttachment(a)}return}
 if(m.type==='close'&&a.host){await this.closeRoom('主控強制關房');return}
 if(m.type==='start'&&a.host&&this.state.phase==='lobby'&&this.sockets().some(w=>!w.deserializeAttachment().host)){this.syncCompanion();this.state.players=this.state.players.filter(p=>p.ai||this.sockets().some(w=>!w.deserializeAttachment().host&&w.deserializeAttachment().id===p.id));this.state.players.forEach((p,i)=>{p.x=gridX(i,this.state.players.length);p.s=0});this.state.phase='race';this.state.start=now+4000;this.state.activity=now;this.last=now;await this.save();await this.schedule(50);this.broadcast(true)}
 if(m.type==='reset'&&a.host&&this.state.phase==='results'){this.state.phase='lobby';this.state.start=0;this.state.activity=now;this.state.players=this.state.players.filter(p=>!p.ai).map(p=>({...racer(p.id,p.name),resume:p.resume}));this.reapLobby();this.syncCompanion();for(const w of this.sockets()){const a=w.deserializeAttachment();delete a.input;w.serializeAttachment(a)}await this.save();await this.schedule(LIMITS.heartbeat);this.broadcast(true)}
 if(m.type==='input'&&!a.host&&this.state.phase==='race'&&now-a.last>=35){a.last=now;const prev=a.input;a.input={steer:Number.isFinite(m.steer)?Math.max(-1,Math.min(1,m.steer)):0,tap:!!m.tap||!!prev?.tap,shake:!!m.shake||!!prev?.shake,at:now};ws.serializeAttachment(a)}}
 async handleAlarm(){this.nextAlarm=null;if(!this.state||this.state.phase==='closed'||await this.expire())return;const now=Date.now();for(const w of this.sockets()){let a=w.deserializeAttachment();if((a.host&&(!a.accessExp||a.accessExp*1000<=now))||now-a.seen>LIMITS.stale){w.serializeAttachment({...a,gone:true});w.close(1000,'Heartbeat timeout')}else if(now-a.pingAt>=LIMITS.heartbeat){a.pingAt=now;a.pingNonce=crypto.randomUUID();w.serializeAttachment(a);this.send(w,{type:'ping',nonce:a.pingNonce})}}
 if(this.reapLobby()){this.syncCompanion();await this.save()}
 const sockets=this.sockets(),players=sockets.filter(w=>!w.deserializeAttachment().host);if(!sockets.some(w=>w.deserializeAttachment().host))this.state.hostMissing||=now;else this.state.hostMissing=0;
 if(!sockets.length||now>=this.state.created+LIMITS.lifetime||(this.state.hostMissing&&now>=this.state.hostMissing+LIMITS.hostGrace)||(this.state.phase!=='race'&&now>=this.state.activity+LIMITS.idle)){await this.closeRoom(!sockets.length?'所有人已離線':'房間逾時自動關閉');return}
 if(this.state.phase==='race'&&!players.length){this.state.emptySince||=now;if(now-this.state.emptySince>=LIMITS.emptyRace){await this.closeRoom('空場自動關閉');return}await this.save();await this.schedule(LIMITS.heartbeat);this.broadcast();return}
 if(this.state.phase==='race'){this.state.emptySince=0;const dt=Math.min(.15,(now-this.last)/1000);this.last=now;this.state.lastTick=now;this.state.stats.ticks++;this.objects??=course(this.state.seed);if(now>=this.state.start){let finishedNow=false;for(const p of this.state.players){const wasFinished=p.finished;const w=players.find(w=>w.deserializeAttachment().id===p.id);if(!w&&!p.ai)continue;const a=w?.deserializeAttachment();let i=p.ai?aiInput(p,(now-this.state.start)/1000,this.objects,Math.max(2,...this.state.players.filter(p=>!p.ai).map(p=>p.tier))):a.input||{};if(!p.ai&&now-(i.at||0)>500)i={};p.steer=i.steer||0;let remaining=dt;while(remaining>0){let d=Math.min(.05,remaining);step(p,i,d,(now-this.state.start)/1000,this.objects);i.tap=false;i.shake=false;remaining-=d}if(a){a.input=i;w.serializeAttachment(a)}if(!wasFinished&&p.finished)finishedNow=true}if(finishedNow)await this.save();if(this.state.players.every(p=>p.finished)||now-this.state.start>600000){this.state.phase='results';this.state.activity=now;await this.save()}}}
 if(now-this.lastSave>=LIMITS.checkpoint)await this.save();await this.schedule(this.state?.phase==='race'?50:LIMITS.heartbeat);this.broadcast()}
 async handleClose(ws){const a=ws.deserializeAttachment();if(a?.cleaned)return;ws.serializeAttachment({...a,gone:true,cleaned:true});try{ws.close()}catch{}if(!this.state||await this.expire())return;if(a?.host&&!this.sockets().some(w=>w.deserializeAttachment().host))this.state.hostMissing||=Date.now();if(!this.sockets().length){await this.closeRoom('所有人已離線');return}if(this.state.phase==='race'&&!this.sockets().some(w=>!w.deserializeAttachment().host))this.state.emptySince||=Date.now();this.reapLobby();this.syncCompanion();await this.save();await this.schedule(LIMITS.heartbeat);this.broadcast()}
 async webSocketError(ws){await this.webSocketClose(ws)}
}
async function route(req,env){const u=new URL(req.url),isHost=u.pathname==='/host'||u.pathname.startsWith('/host/');if(u.hostname.endsWith('.workers.dev'))return new Response('Use the production domain',{status:403});const forwarded=new Request(req);for(const key of ['X-Skigpt-Owner','X-Skigpt-Email','X-Skigpt-Access-Exp','X-Skigpt-Location'])forwarded.headers.delete(key);
 if(isHost){let identity;try{identity=await verifyAccess(req,env)}catch(error){return new Response(error.message,{status:error.status||403,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}})}forwarded.headers.set('X-Skigpt-Owner',identity.sub);forwarded.headers.set('X-Skigpt-Email',identity.email);forwarded.headers.set('X-Skigpt-Access-Exp',String(identity.exp));if(u.pathname==='/host/api/session')return Response.json({email:identity.email,expires:identity.exp},{headers:{'Cache-Control':'no-store'}});
 if(u.pathname==='/host'||u.pathname==='/host/'){const response=await env.ASSETS.fetch(new Request(new URL('/',u),req));const headers=new Headers(response.headers);headers.set('Cache-Control','private, no-store');return new Response(response.body,{status:response.status,headers})}}
 const pathname=isHost?u.pathname.slice(5):u.pathname,match=pathname.match(/^\/api\/rooms\/([A-Z0-9]{6})(\/(?:create|close|ticket))?$/);
 if(match){if(req.headers.get('Origin')&&req.headers.get('Origin')!==u.origin)return new Response('Origin denied',{status:403});if(((match[2]&&match[2]!=='/ticket')||u.searchParams.has('host'))&&!isHost)return new Response('Host actions require Cloudflare Access at /host',{status:403});if(match[2]&&req.method!=='POST')return new Response('Method not allowed',{status:405});if(!validJoin(u))return new Response('Invalid parameters',{status:400});if(!match[2]&&(req.method!=='GET'||req.headers.get('Upgrade')!=='websocket'))return new Response('WebSocket GET required',{status:426});if(u.searchParams.has('resume')||u.searchParams.has('host'))return new Response('Use a connection ticket',{status:400});if(!match[2]&&(!/^[A-Za-z0-9_-]{36}$/.test(u.searchParams.get('ticket')||'')||[...u.searchParams.keys()].some(k=>k!=='ticket')))return new Response('Connection ticket required',{status:400});let denied=null;if(match[2]==='/create')denied=await edgeLimit(env.HOST_CREATE_LIMIT,forwarded.headers.get('X-Skigpt-Owner'));else if(!match[2]||match[2]==='/ticket')denied=await edgeLimit(env.JOIN_LIMIT,'join:'+ (req.headers.get('CF-Connecting-IP')||'unknown'));if(denied)return denied;const hint=['wnam','enam','sam','weur','eeur','apac','apac-ne','apac-se','oc','afr','me'].includes(env.DO_LOCATION_HINT)?env.DO_LOCATION_HINT:null;
 if(match[2]==='/create')forwarded.headers.set('X-Skigpt-Location',JSON.stringify({hostname:u.hostname,zone:env.CF_ZONE_NAME||null,zoneSource:env.CF_ZONE_NAME?'configured':'not-configured',ingressColo:req.cf?.colo||null,clientCountry:req.cf?.country||null,clientRegion:req.cf?.region||null,placementHint:hint||'automatic',actualDoRegion:null}));
 return env.ROOMS.get(env.ROOMS.idFromName(match[1]),hint?{locationHint:hint}:{}).fetch(forwarded)}if(isHost)return new Response('Not found',{status:404});return env.ASSETS.fetch(req)}
export default {async fetch(req,env){return secureResponse(await route(req,env),req)}};

