import { DurableObject } from 'cloudflare:workers';
import {course,racer,step,MAX_PLAYERS} from '../game/physics.mjs';
export class RaceRoom extends DurableObject{
 constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.state=null;this.inputs=new Map();this.last=Date.now();ctx.blockConcurrencyWhile(async()=>{this.state=await ctx.storage.get('room')||null;this.last=this.state?.lastTick||Date.now()})}
 async fetch(req){let u=new URL(req.url);if(u.pathname.endsWith('/create')){if(this.state)return Response.json({error:'Room exists'},{status:409});let token=crypto.randomUUID();this.state={token,seed:crypto.getRandomValues(new Uint32Array(1))[0],phase:'lobby',start:0,players:[],created:Date.now()};await this.ctx.storage.put('room',this.state);await this.ctx.storage.setAlarm(Date.now()+3600000);return Response.json({token})}if(!this.state)return Response.json({error:'找不到房間'},{status:404});if(req.headers.get('Upgrade')!=='websocket')return new Response('WebSocket required',{status:426});if(this.ctx.getWebSockets().length>MAX_PLAYERS+3)return new Response('房間已滿',{status:429});let pair=new WebSocketPair();let [client,server]=Object.values(pair);let host=u.searchParams.get('host')===this.state.token;let id=u.searchParams.get('id')||crypto.randomUUID();let existing=this.state.players.find(p=>p.id===id);let resume=u.searchParams.get('resume');if(!host&&existing&&existing.resume!==resume)return new Response('無法恢復此玩家',{status:403});if(!host&&!existing&&this.state.phase!=='lobby')return new Response('比賽已開始',{status:409});if(!host&&!existing&&this.state.players.length>=MAX_PLAYERS)return new Response('房間已滿',{status:429});this.ctx.acceptWebSocket(server);if(!host&&!existing){existing={...racer(id,(u.searchParams.get('name')||'滑雪者').slice(0,16)),resume:crypto.randomUUID()};this.state.players.push(existing)}server.serializeAttachment({id,host,last:0});server.send(JSON.stringify({type:'welcome',id,resume:existing?.resume,host}));await this.ctx.storage.put('room',this.state);this.broadcast();return new Response(null,{status:101,webSocket:client})}
 snapshot(){return {type:'state',seed:this.state.seed,phase:this.state.phase,start:this.state.start,now:Date.now(),players:this.state.players.map(({resume,...p})=>({...p,online:this.ctx.getWebSockets().some(w=>w.deserializeAttachment()?.id===p.id)}))}}
 broadcast(){let msg=JSON.stringify(this.snapshot());for(let ws of this.ctx.getWebSockets())try{ws.send(msg)}catch{}}
 async webSocketMessage(ws,data){if(typeof data!=='string'||data.length>512)return;let m;try{m=JSON.parse(data)}catch{return}let a=ws.deserializeAttachment();if(m.type==='start'&&a.host&&this.state.phase==='lobby'&&this.state.players.length){this.state.phase='race';this.state.start=Date.now()+4000;this.last=Date.now();await this.ctx.storage.put('room',this.state);await this.ctx.storage.setAlarm(Date.now()+50);this.broadcast()}if(m.type==='reset'&&a.host){this.state.phase='lobby';this.state.start=0;this.state.players=this.state.players.map(p=>({...racer(p.id,p.name),resume:p.resume}));this.inputs.clear();await this.ctx.storage.put('room',this.state);await this.ctx.storage.setAlarm(Date.now()+3600000);this.broadcast()}if(m.type==='input'&&!a.host&&Date.now()-a.last>=35){a.last=Date.now();ws.serializeAttachment(a);let prev=this.inputs.get(a.id);a.input={steer:Number.isFinite(m.steer)?Math.max(-1,Math.min(1,m.steer)):0,tap:!!m.tap||!!prev?.tap,shake:!!m.shake||!!prev?.shake,at:Date.now()};this.inputs.set(a.id,a.input);ws.serializeAttachment(a)}}
 async alarm(){if(!this.state)return;let now=Date.now();if(now-this.state.created>3600000){for(let ws of this.ctx.getWebSockets())ws.close(1000,'房間已到期');await this.ctx.storage.deleteAll();this.state=null;return}if(this.state.phase==='race'){let dt=Math.min(.15,(now-this.last)/1000);this.last=now;this.state.lastTick=now;this.objects??=course(this.state.seed);if(now>=this.state.start){for(let p of this.state.players){let peer=this.ctx.getWebSockets().find(w=>w.deserializeAttachment()?.id===p.id);let attachment=peer?.deserializeAttachment();let i=this.inputs.get(p.id)||attachment?.input||{};if(now-(i.at||0)>500)i={};let remaining=dt;while(remaining>0){let d=Math.min(.05,remaining);step(p,i,d,(now-this.state.start)/1000,this.objects);i.tap=false;i.shake=false;remaining-=d}if(attachment){attachment.input=i;peer.serializeAttachment(attachment)}}if(this.state.players.every(p=>p.finished)||now-this.state.start>600000)this.state.phase='results'}this.broadcast();await this.ctx.storage.put('room',this.state);await this.ctx.storage.setAlarm(now+(this.state.phase==='race'?50:3600000))}}
 webSocketClose(ws){try{ws.close()}catch{}if(this.state)this.broadcast()}
 webSocketError(ws){try{ws.close()}catch{}}
}
export default {async fetch(req,env){let u=new URL(req.url);let match=u.pathname.match(/^\/api\/rooms\/([A-Z0-9]{6})(\/create)?$/);if(match){if(req.headers.get('Origin')&&req.headers.get('Origin')!==u.origin)return new Response('Origin denied',{status:403});if(match[2]&&req.method!=='POST')return new Response('Method not allowed',{status:405});return env.ROOMS.get(env.ROOMS.idFromName(match[1])).fetch(req)}return env.ASSETS.fetch(req)}};
