import { DurableObject } from 'cloudflare:workers';
import {verifyAccess} from './access.mjs';
import {AI_ID,companion,aiInput} from '../game/ai.mjs';
import {course,racer,step,MAX_PLAYERS} from '../game/physics.mjs';
export const LIMITS={heartbeat:15000,stale:45000,hostGrace:60000,emptyRace:30000,idle:300000,lifetime:3600000,checkpoint:2000};
export class RaceRoom extends DurableObject{
 constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.state=null;this.queue=Promise.resolve();this.last=Date.now();this.lastSave=0;this.nextAlarm=null;ctx.blockConcurrencyWhile(async()=>{this.state=await ctx.storage.get('room')||null;this.last=this.state?.lastTick||Date.now();if(this.state){this.state.stats??={rx:0,tx:0,bytes:0,ticks:0,writes:0};this.state.activity??=this.state.created;this.state.hostMissing??=Date.now();for(const w of ctx.getWebSockets()){const a=w.deserializeAttachment();if(a&&a.seen==null)w.serializeAttachment({...a,seen:Date.now(),pingAt:0})}}})}
 run(action){const task=this.queue.then(action);this.queue=task.catch(()=>{});return task}
 fetch(req){return this.run(()=>this.handleFetch(req))}
 webSocketMessage(ws,data){return this.run(()=>this.handleMessage(ws,data))}
 alarm(){return this.run(()=>this.handleAlarm())}
 webSocketClose(ws){return this.run(()=>this.handleClose(ws))}
 sockets(){return this.ctx.getWebSockets().filter(w=>!w.deserializeAttachment()?.gone)}
 async save(){if(!this.state||this.state.phase==='closed')return;this.lastSave=Date.now();this.state.stats.writes++;await this.ctx.storage.put('room',this.state)}
 async schedule(ms){if(!this.state||this.state.phase==='closed')return;this.nextAlarm=Date.now()+ms;await this.ctx.storage.setAlarm(this.nextAlarm)}
 send(w,m){try{const data=JSON.stringify(m);w.send(data);if(this.state){this.state.stats.tx++;this.state.stats.bytes+=new TextEncoder().encode(data).length}}catch{}}
 async closeRoom(reason){if(!this.state)return;this.state.phase='closed';this.nextAlarm=null;await this.ctx.storage.deleteAlarm();await this.ctx.storage.deleteAll();for(const w of this.sockets()){this.send(w,{type:'closed',reason,alarmCancelled:true,dataDeleted:true,closedAt:Date.now()});const a=w.deserializeAttachment();w.serializeAttachment({...a,gone:true});try{w.close(1000,'Room closed')}catch{}}this.state=null;console.log(JSON.stringify({event:'room_closed',reason,alarmCancelled:true,dataDeleted:true,sockets:0}))}
 async handleFetch(req){const u=new URL(req.url);if(u.pathname.endsWith('/create')){if(this.state)return Response.json({error:'Room exists'},{status:409});const owner=req.headers.get('X-Skigpt-Owner');if(!owner)return new Response('Access required',{status:403});const token=crypto.randomUUID(),now=Date.now();this.state={token,owner,hostEmail:req.headers.get('X-Skigpt-Email'),location:JSON.parse(req.headers.get('X-Skigpt-Location')||'{}'),seed:crypto.getRandomValues(new Uint32Array(1))[0],phase:'lobby',start:0,players:[],created:now,activity:now,hostMissing:now,stats:{rx:0,tx:0,bytes:0,ticks:0,writes:0}};await this.save();await this.schedule(LIMITS.heartbeat);return Response.json({token})}
 if(!this.state||this.state.phase==='closed')return Response.json({error:'房間已關閉或不存在'},{status:404});
 if(u.pathname.endsWith('/close')){if(req.headers.get('X-Skigpt-Owner')!==this.state.owner||req.headers.get('Authorization')!==`Bearer ${this.state.token}`)return new Response('Forbidden',{status:403});await this.closeRoom('主控強制關房');return Response.json({closed:true,alarmCancelled:true,dataDeleted:true})}
 if(req.headers.get('Upgrade')!=='websocket')return new Response('WebSocket required',{status:426});if(this.sockets().length>=MAX_PLAYERS+2)return new Response('房間已滿',{status:429});const wantsHost=u.searchParams.has('host');if(wantsHost&&(req.headers.get('X-Skigpt-Owner')!==this.state.owner||u.searchParams.get('host')!==this.state.token))return new Response('Access required',{status:403});const host=wantsHost,id=u.searchParams.get('id')||crypto.randomUUID();if(id===AI_ID)return new Response('Reserved player ID',{status:403});let existing=this.state.players.find(p=>p.id===id);if(!host&&existing&&existing.resume!==u.searchParams.get('resume'))return new Response('無法恢復此玩家',{status:403});if(!host&&!existing&&this.state.phase!=='lobby')return new Response('比賽已開始',{status:409});if(!host&&!existing&&this.state.players.length>=MAX_PLAYERS)return new Response('房間已滿',{status:429});
 for(const w of this.sockets()){const a=w.deserializeAttachment();if(host?a.host:!a.host&&a.id===id){w.serializeAttachment({...a,gone:true});w.close(1000,'Reconnected')}}
 const [client,server]=Object.values(new WebSocketPair());this.ctx.acceptWebSocket(server);if(!host&&!existing){existing={...racer(id,(u.searchParams.get('name')||'滑雪者').slice(0,16)),resume:crypto.randomUUID()};this.state.players.push(existing)}const now=Date.now();server.serializeAttachment({id,host,accessExp:host?Number(req.headers.get('X-Skigpt-Access-Exp')):null,last:0,seen:now,pingAt:now,pingNonce:crypto.randomUUID()});if(host)this.state.hostMissing=0;this.state.emptySince=0;this.state.activity=now;this.syncCompanion();this.send(server,{type:'welcome',id,resume:existing?.resume,host});this.send(server,{type:'ping',nonce:server.deserializeAttachment().pingNonce});await this.save();await this.schedule(this.state.phase==='race'?50:LIMITS.heartbeat);this.broadcast(true);return new Response(null,{status:101,webSocket:client})}
 syncCompanion(){if(this.state?.phase!=='lobby')return;const humans=this.sockets().filter(w=>!w.deserializeAttachment().host).length;this.state.players=this.state.players.filter(p=>!p.ai);if(humans===1)this.state.players.push(companion())}
 snapshot(){const connections=this.sockets();return {type:'state',seed:this.state.seed,phase:this.state.phase,start:this.state.start,now:Date.now(),players:this.state.players.map(({resume,...p})=>{const a=connections.find(w=>{let a=w.deserializeAttachment();return !a.host&&a.id===p.id})?.deserializeAttachment();return {...p,online:p.ai||!!a,ping:a?.rtt??null,pingAt:a?.rttAt??null}})}}
 info(){const s=this.state;return {phase:s.phase,location:{...(s.location||{}),jurisdiction:this.ctx.id?.jurisdiction||null},hostEmail:s.hostEmail||null,aiPlayers:s.players.filter(p=>p.ai).length,connections:this.sockets().length,onlinePlayers:this.sockets().filter(w=>!w.deserializeAttachment().host).length,created:s.created,expires:s.created+LIMITS.lifetime,idleDeadline:s.activity+LIMITS.idle,hostDeadline:s.hostMissing?s.hostMissing+LIMITS.hostGrace:null,nextAlarm:this.nextAlarm,tickHz:s.phase==='race'&&this.sockets().some(w=>!w.deserializeAttachment().host)?20:0,checkpointMs:LIMITS.checkpoint,...s.stats,objectId:this.ctx.id?.toString()||'local-test'}}
 broadcast(force=false){if(!this.state||this.state.phase==='closed')return;const snapshot=this.snapshot();for(const w of this.sockets()){const a=w.deserializeAttachment(),now=Date.now();if(a.host&&!force&&this.state.phase==='race'&&now-(a.dashboardAt||0)<500)continue;a.dashboardAt=now;w.serializeAttachment(a);this.send(w,a.host?{...snapshot,doInfo:this.info()}:snapshot)}}
 async handleMessage(ws,data){if(!this.state||this.state.phase==='closed'||typeof data!=='string'||data.length>512)return;let m;try{m=JSON.parse(data)}catch{return}const a=ws.deserializeAttachment();if(a.gone)return;if(a.host&&(!a.accessExp||a.accessExp*1000<=Date.now())){ws.serializeAttachment({...a,gone:true});ws.close(1008,'Access expired');this.state.hostMissing=Date.now();await this.save();return}this.state.stats.rx++;const now=Date.now();a.seen=now;ws.serializeAttachment(a);
 if(m.type==='pong'){if(m.nonce===a.pingNonce&&a.pingAt){a.rtt=now-a.pingAt;a.rttAt=now;a.pingNonce=null;ws.serializeAttachment(a)}return}
 if(m.type==='close'&&a.host){await this.closeRoom('主控強制關房');return}
 if(m.type==='start'&&a.host&&this.state.phase==='lobby'&&this.sockets().some(w=>!w.deserializeAttachment().host)){this.syncCompanion();this.state.phase='race';this.state.start=now+4000;this.state.activity=now;this.last=now;await this.save();await this.schedule(50);this.broadcast(true)}
 if(m.type==='reset'&&a.host&&this.state.phase==='results'){this.state.phase='lobby';this.state.start=0;this.state.activity=now;this.state.players=this.state.players.filter(p=>!p.ai).map(p=>({...racer(p.id,p.name),resume:p.resume}));this.syncCompanion();for(const w of this.sockets()){const a=w.deserializeAttachment();delete a.input;w.serializeAttachment(a)}await this.save();await this.schedule(LIMITS.heartbeat);this.broadcast(true)}
 if(m.type==='input'&&!a.host&&this.state.phase==='race'&&now-a.last>=35){a.last=now;const prev=a.input;a.input={steer:Number.isFinite(m.steer)?Math.max(-1,Math.min(1,m.steer)):0,tap:!!m.tap||!!prev?.tap,shake:!!m.shake||!!prev?.shake,at:now};ws.serializeAttachment(a)}}
 async handleAlarm(){if(!this.state||this.state.phase==='closed')return;const now=Date.now();for(const w of this.sockets()){let a=w.deserializeAttachment();if((a.host&&(!a.accessExp||a.accessExp*1000<=now))||now-a.seen>LIMITS.stale){w.serializeAttachment({...a,gone:true});w.close(1000,'Heartbeat timeout')}else if(now-a.pingAt>=LIMITS.heartbeat){a.pingAt=now;a.pingNonce=crypto.randomUUID();w.serializeAttachment(a);this.send(w,{type:'ping',nonce:a.pingNonce})}}
 const sockets=this.sockets(),players=sockets.filter(w=>!w.deserializeAttachment().host);if(!sockets.some(w=>w.deserializeAttachment().host))this.state.hostMissing||=now;else this.state.hostMissing=0;
 if(!sockets.length||now>=this.state.created+LIMITS.lifetime||(this.state.hostMissing&&now>=this.state.hostMissing+LIMITS.hostGrace)||(this.state.phase!=='race'&&now>=this.state.activity+LIMITS.idle)){await this.closeRoom(!sockets.length?'所有人已離線':'房間逾時自動關閉');return}
 if(this.state.phase==='race'&&!players.length){this.state.emptySince||=now;if(now-this.state.emptySince>=LIMITS.emptyRace){await this.closeRoom('空場自動關閉');return}await this.save();await this.schedule(LIMITS.heartbeat);this.broadcast();return}
 if(this.state.phase==='race'){this.state.emptySince=0;const dt=Math.min(.15,(now-this.last)/1000);this.last=now;this.state.lastTick=now;this.state.stats.ticks++;this.objects??=course(this.state.seed);if(now>=this.state.start){let finishedNow=false;for(const p of this.state.players){const wasFinished=p.finished;const w=players.find(w=>w.deserializeAttachment().id===p.id);if(!w&&!p.ai)continue;const a=w?.deserializeAttachment();let i=p.ai?aiInput(p,(now-this.state.start)/1000,this.objects,Math.max(2,...this.state.players.filter(p=>!p.ai).map(p=>p.tier))):a.input||{};if(!p.ai&&now-(i.at||0)>500)i={};let remaining=dt;while(remaining>0){let d=Math.min(.05,remaining);step(p,i,d,(now-this.state.start)/1000,this.objects);i.tap=false;i.shake=false;remaining-=d}if(a){a.input=i;w.serializeAttachment(a)}if(!wasFinished&&p.finished)finishedNow=true}if(finishedNow)await this.save();if(this.state.players.every(p=>p.finished)||now-this.state.start>600000){this.state.phase='results';this.state.activity=now;await this.save()}}}
 if(now-this.lastSave>=LIMITS.checkpoint)await this.save();await this.schedule(this.state?.phase==='race'?50:LIMITS.heartbeat);this.broadcast()}
 async handleClose(ws){const a=ws.deserializeAttachment();ws.serializeAttachment({...a,gone:true});try{ws.close()}catch{}if(!this.state)return;if(a.host&&!this.sockets().some(w=>w.deserializeAttachment().host))this.state.hostMissing=Date.now();if(!this.sockets().length){await this.closeRoom('所有人已離線');return}this.syncCompanion();await this.save();this.broadcast()}
 async webSocketError(ws){await this.webSocketClose(ws)}
}
export default {async fetch(req,env){const u=new URL(req.url),isHost=u.pathname==='/host'||u.pathname.startsWith('/host/');const forwarded=new Request(req);for(const key of ['X-Skigpt-Owner','X-Skigpt-Email','X-Skigpt-Access-Exp','X-Skigpt-Location'])forwarded.headers.delete(key);
 if(isHost){let identity;try{identity=await verifyAccess(req,env)}catch(error){return new Response(error.message,{status:error.status||403,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}})}forwarded.headers.set('X-Skigpt-Owner',identity.sub);forwarded.headers.set('X-Skigpt-Email',identity.email);forwarded.headers.set('X-Skigpt-Access-Exp',String(identity.exp));if(u.pathname==='/host/api/session')return Response.json({email:identity.email,expires:identity.exp},{headers:{'Cache-Control':'no-store'}});
 if(u.pathname==='/host'||u.pathname==='/host/'){const response=await env.ASSETS.fetch(new Request(new URL('/',u),req));const headers=new Headers(response.headers);headers.set('Cache-Control','private, no-store');return new Response(response.body,{status:response.status,headers})}}
 const pathname=isHost?u.pathname.slice(5):u.pathname,match=pathname.match(/^\/api\/rooms\/([A-Z0-9]{6})(\/(?:create|close))?$/);
 if(match){if(req.headers.get('Origin')&&req.headers.get('Origin')!==u.origin)return new Response('Origin denied',{status:403});if((match[2]||u.searchParams.has('host'))&&!isHost)return new Response('Host actions require Cloudflare Access at /host',{status:403});if(match[2]&&req.method!=='POST')return new Response('Method not allowed',{status:405});const hint=['wnam','enam','sam','weur','eeur','apac','apac-ne','apac-se','oc','afr','me'].includes(env.DO_LOCATION_HINT)?env.DO_LOCATION_HINT:null;
 if(match[2]==='/create')forwarded.headers.set('X-Skigpt-Location',JSON.stringify({hostname:u.hostname,zone:env.CF_ZONE_NAME||null,zoneSource:env.CF_ZONE_NAME?'configured':'not-configured',ingressColo:req.cf?.colo||null,clientCountry:req.cf?.country||null,clientRegion:req.cf?.region||null,placementHint:hint||'automatic',actualDoRegion:null}));
 return env.ROOMS.get(env.ROOMS.idFromName(match[1]),hint?{locationHint:hint}:{}).fetch(forwarded)}if(isHost)return new Response('Not found',{status:404});return env.ASSETS.fetch(req)}};
